// Marketing copy for each service — powers the SEO "service detail" pages.
// Keyed by the service `id` defined in service-items-pricing-catalog.ts (the single source
// of truth for which services exist and what they cost). Prices, costs, and
// items stay in service-items-pricing-catalog.ts; only page copy lives here.

export interface ServiceContent {
  description?: string
  details?: string
  benefits?: string[]
  overview?: string[]
  howItWorks?: string[]
  faqs?: { question: string; answer: string }[]
}

export const SERVICE_CONTENT: Record<string, ServiceContent> = {
  'website': {
    description: 'A fast, mobile-perfect website designed around how your customers search — built to turn visitors into enquiries.',
    details: 'A complete, professional website built for local businesses — up to five pages, mobile-perfect, and designed to turn visitors into enquiries. We handle everything from your domain and hosting to design, content, and SEO basics, so you launch with a site that looks established, loads fast, and shows up where your customers search.',
    benefits: ['Look established and trustworthy the moment a customer finds you', 'Show up in Google searches for your products and services', 'Turn visitors into enquiries with clear, easy contact options', 'Work beautifully on every phone — where most customers find you', 'Launch fast without hiring a developer or juggling vendors'],
    overview: ['Your website is your storefront on the internet — the first place customers look before they call, visit, or buy. A fast, professional website tells them your business is real, trustworthy, and ready to help, while a slow or missing one quietly sends them to a competitor.', 'This service is built for local businesses that want a complete online presence without hiring a developer. Whether you run a clinic, a salon, a restaurant, or a home-services firm, we design and launch up to five pages that match how your customers actually search — so the people already looking for you find you, and turn into enquiries.'],
    howItWorks: ['We learn your business, customers, and what you want the website to achieve.', 'We design the layout and write clear, search-friendly content for each page.', 'You review the draft and we refine it until you are happy.', 'We launch on your own domain, fully tested and mobile-friendly.'],
    faqs: [{ question: 'How long does it take to build my website?', answer: 'Most websites are designed, built, and live within a few days of confirming your content and branding.' }, { question: 'Can I update the website myself later?', answer: 'Yes. We hand over access and can also handle updates for you under our monthly care plans.' }, { question: 'Do I need to buy a domain and hosting separately?', answer: 'No. Domain, SSL, and hosting are all handled as part of the build, so you have one bill and one partner.' }, { question: 'Will my website work on phones?', answer: 'Absolutely. Every page is tested on mobile and desktop, since most of your customers will visit from a phone.' }],
  },
  'whatsapp': {
    description: 'A chat button on every page so customers message you directly — with a pre-chat name and phone form so you never miss a lead.',
    details: 'Add a WhatsApp chat button to every page of your website so customers can message you in one tap. A pre-chat form captures names and phone numbers so you never miss a lead, even when you are offline.',
    benefits: ['Make it one tap for customers to reach you', 'Never miss a lead — capture names and numbers even when you are busy', 'Reply from WhatsApp, where your customers already are'],
    overview: ['Most customers prefer to message a business rather than fill a form or make a call. A WhatsApp chat button turns that preference into enquiries by letting visitors reach you in a single tap, directly from the page they are already reading.', 'Because the button captures the customer’s name and phone number before they message, you keep a record of every enquiry — even the ones that arrive after hours or while you are busy serving other customers.'],
    howItWorks: ['We add a chat bubble to every page of your website.', 'Visitors tap it and land in a WhatsApp conversation with you.', 'A short pre-chat form captures their name and phone number first.', 'You receive the enquiry and reply straight from WhatsApp.'],
    faqs: [{ question: 'Do customers need WhatsApp to message me?', answer: 'Yes, the button opens WhatsApp on their phone, where most of your customers already are.' }, { question: 'Can I see who messaged me if I miss it?', answer: 'Yes, the pre-chat form records names and numbers so no enquiry is lost.' }, { question: 'Does this work on desktop too?', answer: 'Yes, desktop visitors can open WhatsApp Web to continue the conversation.' }, { question: 'Will it slow down my website?', answer: 'No. The chat button is lightweight and loads without affecting page speed.' }],
  },
  'gbp': {
    description: 'Your Google Business Profile created, verified, and optimized so you appear when local customers search for what you sell.',
    details: 'Get your Google Business Profile created, verified, and fully optimized so you show up when local customers search for what you sell.',
    benefits: ['Appear on Google Maps when local customers search for you', 'Show your business info, photos, and reviews in one trusted place', 'Build credibility with a verified, complete profile'],
    overview: ['When local customers search for a business like yours, Google shows a map with nearby options first. If your Google Business Profile is missing or incomplete, you are invisible in exactly the place buyers are looking.', 'We create, verify, and fully optimize your profile so it shows the right name, hours, photos, and services — helping you appear on Google Maps and build trust before a customer ever visits your website.'],
    howItWorks: ['We set up your profile with accurate business information and categories.', 'We handle the verification steps so Google confirms your business is real.', 'We add photos, service areas, and the details customers look for.', 'Your profile goes live and starts appearing in local searches.'],
    faqs: [{ question: 'Why does Google need to verify my business?', answer: 'Verification proves your business is real and located where you say, which is required before it appears on Maps.' }, { question: 'Can I manage the profile myself afterwards?', answer: 'Yes. We hand over access and can also keep it updated for you.' }, { question: 'Do I need a website for a Google Business Profile?', answer: 'A website helps, but you can start with your profile alone and add a site later.' }, { question: 'How soon will I appear on Google Maps?', answer: 'Once verified, most businesses start appearing within a few days.' }],
  },
  'analytics': {
    description: 'Tracking installed so you can see exactly what is working — visits, enquiries, and calls — in one plain-English report.',
    details: 'See exactly what is working on your website — visits, enquiries, and calls — in one plain-English report.',
    benefits: ['See which marketing is actually bringing customers', 'Understand visits, enquiries, and calls in plain English', 'Stop guessing and spend your budget where it works'],
    overview: ['You cannot improve what you cannot measure. Visit analytics shows you how many people come to your website, where they come from, and — most importantly — whether they call, message, or enquire.', 'Instead of a wall of confusing charts, we turn the numbers into plain-English answers: what is working, what is not, and where to spend your next rupee.'],
    howItWorks: ['We install tracking across your website and goals.', 'We set up conversion tracking for enquiries and calls.', 'We build a simple dashboard you can read at a glance.', 'We explain what the numbers mean and what to do next.'],
    faqs: [{ question: 'Do I need technical skills to read the reports?', answer: 'No. The dashboard is built for business owners, not analysts.' }, { question: 'Can I see which marketing brings customers?', answer: 'Yes, we tag each campaign so you can see exactly which one produces enquiries.' }, { question: 'Is customer data private?', answer: 'Yes. We use privacy-compliant analytics and only you see your business data.' }, { question: 'How often do reports update?', answer: 'Data updates continuously, so you can check anytime.' }],
  },
  'launch-pages': {
    description: 'Additional content pages written, designed, and optimized for SEO — as many as your business needs.',
    details: 'Add extra content pages to your website — written, designed, and SEO-optimized — as many as your business needs to rank for more searches.',
    benefits: ['Rank for more searches by covering more topics', 'Give customers detailed information that builds trust'],
    overview: ['Every extra page on your website is another chance to rank for a search and answer a question. If you only have a homepage, you are missing the customers who search for specific services or locations.', 'We write, design, and publish additional pages tailored to the searches you want to win — each one optimized to load fast and convert visitors into enquiries.'],
    howItWorks: ['We identify the topics and searches worth targeting.', 'We write clear, SEO-friendly content for each new page.', 'We design and build the page to match your website.', 'We publish and check it looks great on every device.'],
    faqs: [{ question: 'How many pages should I add?', answer: 'As many as your services and locations need. We can add pages one at a time or in batches.' }, { question: 'Will new pages rank on Google?', answer: 'Each page is optimized for a specific search, which gives it the best chance to rank.' }, { question: 'Can you update existing pages instead?', answer: 'Yes, we can rewrite and improve your current pages too.' }, { question: 'Do I need to provide the content?', answer: 'No. We research and write the content for you.' }],
  },
  'launch-photos': {
    description: 'Professionally sourced and optimized images that make your site look polished and load fast.',
    details: 'Professionally sourced and optimized images that make your website look polished and load fast, without hiring a photographer.',
    benefits: ['Make your website look polished and professional', 'Keep pages loading fast so customers do not leave'],
    overview: ['Photos are the fastest way to show customers what your business is like. Blurry or stock-looking images make you look unprofessional, while clean, optimized photos build instant trust.', 'We source and prepare professional images that fit your brand, then compress them so they look sharp without slowing your website down.'],
    howItWorks: ['We review your website and choose where new photos are needed.', 'We source licensed, high-quality images that match your business.', 'We optimize each image for fast loading on phones and desktops.', 'We place them on your site with proper captions and descriptions.'],
    faqs: [{ question: 'Can I use my own photos?', answer: 'Yes, we can optimize and use photos you already have, or source new ones.' }, { question: 'Will large photos slow my site down?', answer: 'No. We compress every image so pages load quickly.' }, { question: 'Do the photos have legal rights?', answer: 'Yes, we only use properly licensed images.' }, { question: 'How many photos can I add?', answer: 'As many as your site needs. We work in batches to keep it affordable.' }],
  },
  'launch-domain': {
    description: 'Your domain connected, configured, and secured so everything points to your site.',
    details: 'Your custom domain connected, configured, and secured so every visitor lands on your website reliably.',
    benefits: ['Give customers a reliable address they can trust', 'Protect your site with a secure connection'],
    overview: ['Your domain is your address on the internet — it is what customers type, remember, and trust. A properly configured domain makes sure every visitor reaches your site reliably and securely.', 'We connect your domain, set up the necessary records, and make sure security certificates renew automatically so your site never shows a warning or goes offline.'],
    howItWorks: ['We review or register your domain name.', 'We configure the records so it points to your website.', 'We set up secure connections and email forwarding.', 'We verify everything works before going live.'],
    faqs: [{ question: 'Can I keep my existing domain?', answer: 'Yes, we connect your current domain to your website.' }, { question: 'What if I do not have a domain yet?', answer: 'We help you choose and register one as part of the setup.' }, { question: 'Will my site be secure?', answer: 'Yes, SSL is configured and renews automatically.' }, { question: 'Do I need to understand DNS?', answer: 'No. We handle all the technical setup for you.' }],
  },
  'gbp-optimise': {
    description: 'Your profile polished with photos, categories, offers, and posts so it stands out against every competitor in your area.',
    details: 'Keep your Google Business Profile active and climbing with weekly posts, fresh photos, and review generation — so you stand out against every competitor in your area.',
    benefits: ['Stay visible and active on Google with fresh posts and photos', 'Stand out against competitors in your area', 'Turn happy customers into visible reviews'],
    overview: ['A Google Business Profile is not a set-it-and-forget-it listing. Profiles that post fresh photos, offers, and updates regularly get more views, calls, and visits than inactive competitors.', 'This monthly service keeps your profile active and climbing — with regular posts, fresh photos, and review generation that keep you ahead of every other business in your area.'],
    howItWorks: ['We plan a monthly calendar of posts, offers, and updates.', 'We create and publish fresh content to your profile.', 'We encourage and manage customer reviews.', 'We report your rankings and visibility each month.'],
    faqs: [{ question: 'How often do you post?', answer: 'We publish roughly four posts a month, plus photo and offer updates.' }, { question: 'Will this help me rank higher on Maps?', answer: 'Active, optimized profiles tend to rank better than inactive competitors.' }, { question: 'Do you reply to customer reviews?', answer: 'Yes, we draft professional replies you can approve.' }, { question: 'Can I see the results?', answer: 'You get a monthly report showing views, calls, and ranking changes.' }],
  },
  'local-seo': {
    description: 'Rank for searches like plumber near me in your city. We optimize your presence so the people already looking for you find you first.',
    details: 'Rank on Google Maps for searches like \'plumber near me\' in your city. We optimize your presence so the people already searching for you find you first.',
    benefits: ['Rank for \'near me\' searches in your city', 'Get found by customers already looking for what you sell', 'Win more local business over competitors who ignore SEO'],
    overview: ['When someone in your city searches for what you sell, you want to be the business they see first. Local SEO makes that happen by optimizing your online presence for exactly those nearby searches.', 'This service combines keyword research, directory listings, and consistency checks so search engines trust your business and show it to the customers already looking for you.'],
    howItWorks: ['We research the local keywords your customers actually search.', 'We list your business consistently across relevant directories.', 'We audit and fix your name, address, and phone details everywhere.', 'We build local authority and track your rankings monthly.'],
    faqs: [{ question: 'How is local SEO different from regular SEO?', answer: 'Local SEO focuses on ranking for searches near your location, like "dentist near me".' }, { question: 'How long until I see results?', answer: 'Local SEO builds over weeks and months, with steady gains rather than overnight jumps.' }, { question: 'Do I need a website for this to work?', answer: 'A website helps, but your Google profile and listings can rank even without one.' }, { question: 'What do directory citations do?', answer: 'Consistent listings build trust with Google and help customers find you in more places.' }],
  },
  'whatsapp-book': {
    description: 'Instant auto-replies, quick-reply menus, and a booking flow so customers help themselves 24/7.',
    details: 'Automate your WhatsApp with instant auto-replies, quick-reply menus, and a booking flow so customers help themselves 24/7.',
    benefits: ['Answer customers instantly, even outside business hours', 'Save your team hours of repetitive replies', 'Let customers help themselves 24/7'],
    overview: ['Your customers expect instant answers, even when you are closed or busy. WhatsApp automation replies to them immediately, answers common questions, and can even take bookings — without you typing a single message.', 'This is about saving time and never losing a lead. Instead of missed calls and delayed replies, every enquiry gets an instant, helpful response around the clock.'],
    howItWorks: ['We set up your WhatsApp business account and tools.', 'We create instant greeting and away-message flows.', 'We build quick-reply menus for common questions.', 'We add a booking flow and hand over the dashboard.'],
    faqs: [{ question: 'Will automation feel robotic to customers?', answer: 'No. We write natural, on-brand replies that sound like your team.' }, { question: 'Can customers still reach a human?', answer: 'Yes, the flow always offers a path to a real person.' }, { question: 'Does this work 24/7?', answer: 'Yes, automated replies run around the clock.' }, { question: 'Do I need special software?', answer: 'We set up and manage the platform as part of the service.' }],
  },
  'reviews': {
    description: 'We ask happy customers for reviews after every sale, building the social proof that turns searchers into customers.',
    details: 'Turn happy customers into visible reviews with automatic requests after every sale — building the social proof that turns searchers into buyers.',
    benefits: ['Build social proof that turns searchers into customers', 'Rank higher with more fresh reviews', 'Handle negative feedback privately before it hurts your reputation'],
    overview: ['Before most customers choose a business, they check its reviews. A steady stream of recent, positive reviews is one of the strongest signals that your business is trustworthy.', 'We make asking for reviews automatic — a happy customer finishes their purchase and immediately gets a polite request to share their experience, building your reputation without you having to chase anyone.'],
    howItWorks: ['We set up a simple review link and redirect to your profile.', 'We automate polite review requests after each sale.', 'We monitor new reviews and flag anything needing attention.', 'We showcase your best reviews on your website.'],
    faqs: [{ question: 'Is it appropriate to ask customers for reviews?', answer: 'Yes. A polite, timely request is normal and most happy customers are glad to help.' }, { question: 'What about negative reviews?', answer: 'We help you respond professionally and route feedback privately so it is resolved.' }, { question: 'Which platforms do you cover?', answer: 'Primarily Google, and we can include Facebook and others.' }, { question: 'Can I see all my reviews in one place?', answer: 'Yes, we provide a dashboard and monthly summary.' }],
  },
  'social': {
    description: 'A steady stream of posts, creatives, and captions that keep your business top-of-mind with the people who matter.',
    details: 'A steady stream of branded posts, creatives, and captions that keep your business top-of-mind on social media.',
    benefits: ['Stay top-of-mind with a consistent presence', 'Show your work, offers, and personality to new audiences', 'Build a following without spending hours on content'],
    overview: ['Customers research businesses on social media before they buy. A consistent stream of posts keeps your business in front of them and shows you are active, credible, and worth choosing.', 'This service handles the work you never have time for — planning, writing, and designing a month of posts — so your social presence grows without eating your schedule.'],
    howItWorks: ['We plan a monthly content calendar around your business.', 'We write captions and design on-brand creatives.', 'We publish posts on a consistent schedule.', 'We monitor engagement and report results monthly.'],
    faqs: [{ question: 'How many posts do I get each month?', answer: 'Eight posts per month, planned and designed for you.' }, { question: 'Do I need to approve posts before they go live?', answer: 'Yes, we share the calendar and creatives for your approval first.' }, { question: 'Which platforms do you cover?', answer: 'Instagram and Facebook, with content reusable for others.' }, { question: 'Can you use my own photos?', answer: 'Yes, we can use your photos or source licensed images.' }],
  },
  'seo-report': {
    description: 'A plain-English report on keyword positions, broken links, and competitors — with actions, not jargon.',
    details: 'A plain-English monthly report on your keyword positions, broken links, and competitors — with clear actions, not jargon.',
    benefits: ['Know exactly where your website stands each month', 'Get clear actions instead of confusing jargon', 'Track what is improving so you can invest with confidence'],
    overview: ['Most businesses have no idea whether their website is improving or quietly losing ground. A monthly SEO report answers that question in plain language, with clear actions you can actually act on.', 'We track your keyword positions, check for broken links and technical issues, and compare you against competitors — then summarize what matters and what to do next.'],
    howItWorks: ['We pull data from Search Console and tracking tools.', 'We check your keyword positions and site health.', 'We compare your performance against competitors.', 'We deliver a plain-English report with recommendations.'],
    faqs: [{ question: 'Do I need to understand SEO to use the report?', answer: 'No. The report is written for business owners, with clear recommendations.' }, { question: 'How often do I get a report?', answer: 'Monthly, so you can track progress over time.' }, { question: 'Will you fix the issues you find?', answer: 'We can, or we can hand clear instructions to your team.' }, { question: 'What tools do you use?', answer: 'A mix of Google’s free tools and professional SEO software.' }],
  },
  'google-ads-setup': {
    description: 'Ad campaigns that put you in front of people searching for your service right now — and pay only for results.',
    details: 'Launch Google Ads campaigns that put you in front of people searching for your service right now — and pay only for results.',
    benefits: ['Put your business in front of people searching right now', 'Pay only for real results', 'Start generating leads immediately'],
    overview: ['Search ads put your business in front of people who are actively looking for what you sell — right at the moment they are ready to buy. Unlike a website that takes time to rank, ads can start bringing enquiries within days.', 'We set up your campaigns the right way from day one: the right keywords, compelling ad copy, and conversion tracking, so you only pay for real results and can see exactly what each rupee returns.'],
    howItWorks: ['We research the keywords your customers search for.', 'We write ad copy and set up Search, Maps, and video campaigns.', 'We configure conversion tracking and budgets.', 'We launch and review early performance with you.'],
    faqs: [{ question: 'How much does the ad budget cost?', answer: 'Your ad budget is paid directly to Google — typically a few thousand rupees a month to start.' }, { question: 'How soon will I get enquiries?', answer: 'Campaigns can start producing clicks and calls within days of launch.' }, { question: 'Do you manage the ads after setup?', answer: 'Setup is separate from ongoing management, which we also offer monthly.' }, { question: 'Can I pause the ads anytime?', answer: 'Yes, you control the budget and can pause whenever you like.' }],
  },
  'meta-ads-setup': {
    description: 'Facebook, Instagram, and WhatsApp ads set up to reach the exact audience you want — with pixel and conversion tracking.',
    details: 'Set up Facebook, Instagram, and WhatsApp ads to reach your exact audience — with pixel and conversion tracking from day one.',
    benefits: ['Reach the exact audience most likely to buy from you', 'Appear on Facebook, Instagram, and WhatsApp', 'Track every rupee against real conversions'],
    overview: ['Facebook and Instagram reach people who are not actively searching but are exactly the right fit for your business. Meta ads put your offer in front of that audience and drive them to message, call, or buy.', 'We set up your ad account, pixel, and campaigns across Facebook, Instagram, and WhatsApp — with tracking in place so you know precisely what each rupee of spend returns.'],
    howItWorks: ['We set up your Meta Business account and tracking pixel.', 'We research your ideal audience and build targeting.', 'We create image and video ads for Feed, Stories, and Reels.', 'We launch campaigns and review performance with you.'],
    faqs: [{ question: 'How much ad budget do I need?', answer: 'Budgets are paid directly to Meta and can start small, scaling up as results come in.' }, { question: 'Which platforms do the ads run on?', answer: 'Facebook, Instagram, WhatsApp, and Messenger.' }, { question: 'Do I need a video for the ads?', answer: 'No, we can design image ads or use simple video formats.' }, { question: 'Can you target people near my business?', answer: 'Yes, we can target by location, interests, and behaviors.' }],
  },
  'growth-city': {
    description: 'A dedicated landing page, citations, and listings so you rank in the next city you want to win.',
    details: 'Expand into the next city with a dedicated landing page, local listings, and citations so you rank where you want to win.',
    benefits: ['Win customers in the next city you want to grow into', 'Rank locally without opening a physical branch'],
    overview: ['If you are ready to win customers in a new city, you need more than a hope — you need a local presence there. This service builds a dedicated landing page and local listings so you rank in the next market you target.', 'We research that city’s search behavior, build a page tailored to it, and list your business locally, so customers there find you as easily as they find your competitors.'],
    howItWorks: ['We research the keywords and competitors in your target city.', 'We design and build a dedicated landing page for that city.', 'We set up local listings and citations for the new area.', 'We add local schema so search engines understand your coverage.'],
    faqs: [{ question: 'Can I target more than one city?', answer: 'Yes, we can build a presence across multiple cities over time.' }, { question: 'Do I need a physical office there?', answer: 'Not necessarily. Many service businesses rank in nearby cities without a branch.' }, { question: 'How is this different from my main website?', answer: 'It adds a dedicated page and listings optimized for the new city’s searches.' }, { question: 'How long until I rank in the new city?', answer: 'Local rankings build over weeks to months, depending on competition.' }],
  },
  'account-manager': {
    description: 'One person who knows your business, with monthly strategy calls and a quarterly review of what is working.',
    details: 'Get one dedicated person who knows your business, with monthly strategy calls and quarterly reviews of what\'s working.',
    benefits: ['Have one person who truly knows your business', 'Stay on track with monthly strategy and clear reporting', 'Never wonder what is being done or why'],
    overview: ['When your marketing is split across many tools and people, it is easy to lose track of what is actually happening. A dedicated growth manager gives you one person who knows your business and keeps everything moving.', 'You get a single point of contact, regular strategy calls, and clear reporting — so you always know what is being done, why, and what is working.'],
    howItWorks: ['We assign a manager who learns your business and goals.', 'You get a priority channel for questions and requests.', 'You receive monthly strategy calls and performance reports.', 'We review progress quarterly and adjust the plan.'],
    faqs: [{ question: 'How is this different from normal support?', answer: 'You get one dedicated person with priority access and proactive strategy.' }, { question: 'How often do we talk?', answer: 'At least monthly, with weekly updates and a quarterly review.' }, { question: 'Can the manager coordinate with my team?', answer: 'Yes, they can work directly with your staff as needed.' }, { question: 'What if my needs change?', answer: 'Your manager adjusts the plan with you as your business evolves.' }],
  },
  'unlimited-updates': {
    description: 'Unlimited content and page updates every month — change a phone number, add a page, swap a photo, no extra bills.',
    details: 'Make unlimited content and page updates every month — change a phone number, add a page, or swap a photo with no extra bills.',
    benefits: ['Keep your website accurate and current without extra bills', 'Make changes as fast as your business changes', 'No more waiting or surprise invoices for small edits'],
    overview: ['A website that says the wrong phone number or lists an outdated menu quietly costs you customers. Unlimited updates mean you never have to hesitate before asking for a change.', 'Change a price, add a page, swap a photo, or update your hours — whenever you need, with no surprise invoices at the end of the month.'],
    howItWorks: ['You send us the change you need through a simple channel.', 'We make the update and review it for accuracy.', 'We publish and test on every device.', 'You request more changes as often as needed.'],
    faqs: [{ question: 'Is it really unlimited?', answer: 'Yes, within fair use — normal content and page updates are unlimited each month.' }, { question: 'How fast are updates completed?', answer: 'Most simple changes are done within a business day or two.' }, { question: 'What counts as an update?', answer: 'Text, images, pages, hours, prices, and similar content changes.' }, { question: 'Can I do updates myself too?', answer: 'Yes, you keep access and can also make changes on your own.' }],
  },
  'social-reels': {
    description: 'Short-form reels and stories that show your business in motion and reach new audiences.',
    details: 'Short-form reels and stories that show your business in motion and reach new audiences on Instagram and Facebook.',
    benefits: ['Reach new audiences with short-form video', 'Show your business in motion — not just static posts'],
    overview: ['Short-form video is the fastest-growing way to reach new customers. Reels and stories show your business in motion — the food being plated, the transformation, the behind-the-scenes — in a way static posts cannot.', 'We handle the ideas, editing, and posting, so your brand appears where people are watching, without you needing to be on camera every day.'],
    howItWorks: ['We brainstorm reel ideas and storyboards for your business.', 'We source footage and edit it into polished short videos.', 'We add music, captions, and on-brand graphics.', 'We schedule and post, then track engagement.'],
    faqs: [{ question: 'Do I need to appear in the videos?', answer: 'Not necessarily. We can use your products, space, or team footage.' }, { question: 'Where do you get the footage?', answer: 'From you, or licensed stock footage we source for you.' }, { question: 'How many reels do I get?', answer: 'We work to a monthly schedule agreed with you.' }, { question: 'Will reels help me reach new people?', answer: 'Yes, short video tends to reach beyond your existing followers.' }],
  },
  'google-ads-management': {
    description: 'Ongoing bid, keyword, and creative optimization so your ad spend keeps paying for itself.',
    details: 'Ongoing bid, keyword, and creative optimization so your Google ad spend keeps paying for itself.',
    benefits: ['Keep your ad spend paying for itself', 'Improve results every week with ongoing optimization', 'Get a clear monthly view of performance'],
    overview: ['Launching ads is only the start. Without ongoing optimization, costs creep up and results slip as competitors change and search behavior shifts.', 'This service keeps your campaigns sharp every week — refining keywords, testing ads, and pruning waste — so your budget keeps working as hard as possible.'],
    howItWorks: ['We monitor your campaigns and search terms weekly.', 'We adjust bids and add negative keywords to cut waste.', 'We test new ad variations and refresh creatives.', 'We report performance and improvements monthly.'],
    faqs: [{ question: 'How much budget should I set?', answer: 'It depends on your market, but we recommend a monthly budget you are comfortable sustaining.' }, { question: 'Will you reduce my cost per lead?', answer: 'We continuously optimize to improve results and lower wasted spend.' }, { question: 'Do I still pay for the ad budget separately?', answer: 'Yes, ad spend is paid directly to Google.' }, { question: 'Can I see what you change?', answer: 'Yes, you get a monthly report of changes and performance.' }],
  },
  'meta-ads-management': {
    description: 'Ongoing audience, creative, and budget optimization across Facebook, Instagram, and WhatsApp ads.',
    details: 'Ongoing audience, creative, and budget optimization across Facebook, Instagram, and WhatsApp ads.',
    benefits: ['Keep ads fresh and effective across Meta platforms', 'Stop wasting budget on the wrong audiences'],
    overview: ['Meta ad performance decays over time — audiences tire, creatives fatigue, and costs rise. Ongoing management keeps your Facebook and Instagram ads fresh and efficient.', 'We refresh creatives, refine audiences, and test new angles monthly, so your campaigns stay profitable instead of slowly losing steam.'],
    howItWorks: ['We review your campaigns and audience performance.', 'We refresh ad creatives and test new variations.', 'We adjust targeting and prune underperforming segments.', 'We report results and next steps monthly.'],
    faqs: [{ question: 'How often are ads refreshed?', answer: 'We refresh creatives and test new variations every month.' }, { question: 'Can you reduce my cost per result?', answer: 'Yes, ongoing testing and optimization aim to improve efficiency.' }, { question: 'Which platforms are covered?', answer: 'Facebook, Instagram, WhatsApp, and Messenger.' }, { question: 'Do I approve changes before they go live?', answer: 'We keep you informed, with major changes shared for approval.' }],
  },
  'competitor': {
    description: 'A clear picture of what your competitors are doing — and the gaps you can own.',
    details: 'Get a clear picture of what your competitors are doing — and the gaps you can own.',
    benefits: ['Understand exactly what your competitors are doing', 'Find the gaps you can own and win'],
    overview: ['You cannot beat competitors you do not understand. A competitor analysis shows you exactly what they are doing online — where they are strong, where they are weak, and where you can win.', 'We audit their websites, ads, and visibility, then translate the findings into clear opportunities your business can act on.'],
    howItWorks: ['We identify your top competitors in the market.', 'We audit their websites, ads, and online presence.', 'We map their strengths, weaknesses, and gaps.', 'We deliver a report with clear recommendations.'],
    faqs: [{ question: 'How many competitors do you analyze?', answer: 'Typically your top three, or more if your market needs it.' }, { question: 'What do I do with the report?', answer: 'It gives you a clear list of opportunities and gaps to act on.' }, { question: 'Is this a one-time analysis?', answer: 'Yes, though it can be repeated as your market changes.' }, { question: 'Do you implement the recommendations too?', answer: 'We can, as part of our other marketing services.' }],
  },
  'scale-priority': {
    description: 'A priority support queue with a 2-hour response time so nothing waits.',
    details: 'Jump the queue with priority support and a 2-hour response time so nothing waits.',
    benefits: ['Get answers in hours, not days', 'Keep your business moving without waiting on support'],
    overview: ['When something on your website breaks or a customer is waiting, hours feel like days. Priority support puts your requests at the front of the queue with a guaranteed fast response.', 'This is for businesses that cannot afford to wait — you get a direct line and a response-time commitment that keeps your business moving.'],
    howItWorks: ['Your requests are routed to a priority support queue.', 'You get a guaranteed fast response during business hours.', 'Urgent issues are escalated to the right people immediately.', 'You stay informed until the issue is resolved.'],
    faqs: [{ question: 'What is the response time?', answer: 'We commit to responding within two hours during business hours.' }, { question: 'What counts as urgent?', answer: 'Anything affecting your website being down or customers being unable to reach you.' }, { question: 'Is this available outside business hours?', answer: 'Business-hours priority is standard, with escalation options available.' }, { question: 'Can my team use this too?', answer: 'Yes, your whole team can route requests through the priority channel.' }],
  },
  'scale-multi': {
    description: 'Set up and manage your presence across multiple locations, each with its own listing and page.',
    details: 'Set up and manage your presence across multiple locations, each with its own listing and page.',
    benefits: ['Manage every location consistently from one place', 'Win customers in every area you serve'],
    overview: ['If your business serves several locations, you need a presence in each one. Multi-location management sets up and maintains a Google profile and landing page for every branch or service area.', 'This keeps your listings consistent and your brand strong everywhere you operate, so customers in each area can find and trust you.'],
    howItWorks: ['We set up a Google Business Profile for each location.', 'We build a landing page for every location or area.', 'We add local citations and schema for each.', 'We keep listings consistent and updated.'],
    faqs: [{ question: 'How many locations can I manage?', answer: 'As many as you operate, each with its own profile and page.' }, { question: 'Do I need a separate website for each?', answer: 'No, dedicated landing pages on your existing site work well.' }, { question: 'Will this hurt my main website’s rankings?', answer: 'No, when done correctly it strengthens your overall local presence.' }, { question: 'Can you update listings as locations change?', answer: 'Yes, we keep every listing accurate as your business grows.' }],
  },
  'business-email': {
    description: 'A professional email that matches your domain. No more Gmail for business.',
    details: 'Get a professional email that matches your domain — no more Gmail for business — with everything configured and authenticated.',
    benefits: ['Look professional with an email that matches your domain', 'Build trust that a free Gmail address can\'t'],
    overview: ['A business email on your own domain — like hello@yourbusiness.com — signals professionalism in a way a free Gmail address never can. Customers and partners take you more seriously.', 'We set up your professional email, connect it to your domain, and configure it so your messages are authenticated and less likely to land in spam.'],
    howItWorks: ['We create your email account on your domain.', 'We verify the domain and configure the mail records.', 'We add authentication so your emails are trusted.', 'We help you set it up on your phone and computer.'],
    faqs: [{ question: 'Why do I need a domain email?', answer: 'It builds trust and protects your brand, unlike a free personal address.' }, { question: 'Can I have multiple email addresses?', answer: 'Yes, you can have addresses for different roles or team members.' }, { question: 'Will my emails go to spam?', answer: 'We configure authentication to maximize deliverability.' }, { question: 'Which email provider do you use?', answer: 'A reliable business provider, set up and managed for you.' }],
  },
  'staff-training': {
    description: 'A 1–2 hour session that teaches your team to reply, post, and manage everything themselves.',
    details: 'A 1–2 hour session that teaches your team to reply, post, and manage everything themselves.',
    benefits: ['Empower your team to manage things themselves', 'Reduce dependence on outside help for daily tasks'],
    overview: ['Your team is on the front line of your digital presence — replying on WhatsApp, posting updates, and managing enquiries. A short training session gives them the confidence to do it well.', 'We walk your staff through the tools they use every day, share ready-made reply templates, and leave behind a quick-reference guide so nothing is forgotten.'],
    howItWorks: ['We understand which tools your team uses day to day.', 'We prepare guides and reply templates for each one.', 'We deliver a live 1–2 hour hands-on session.', 'We leave a cheat sheet your team can refer to later.'],
    faqs: [{ question: 'How long is the training?', answer: 'One to two hours, focused on your team’s actual daily tools.' }, { question: 'Is it in person or online?', answer: 'Online works well, and in person can be arranged if you are local.' }, { question: 'What do we get to keep?', answer: 'Guides, templates, and a quick-reference cheat sheet.' }, { question: 'Can we record the session?', answer: 'Yes, so new staff can watch it later.' }],
  },
  'branding-identity': {
    description: 'A professional logo and brand colors you will be proud to show — three concepts, refined until you love it.',
    details: 'A professional logo and brand identity you\'ll be proud to show — three concepts, refined until you love it.',
    benefits: ['Look established and memorable across every touchpoint', 'Build instant recognition and trust'],
    overview: ['Your logo and brand are the first impression customers have of your business. A consistent, professional identity makes you memorable and trustworthy across your website, social media, and print.', 'We design a logo and brand system — colors, fonts, and variations — so every asset you produce looks like it belongs to one confident, established business.'],
    howItWorks: ['We learn about your business, customers, and style preferences.', 'We design three logo concepts for you to choose from.', 'You pick a direction and we refine it with revisions.', 'We deliver the full brand kit with guidelines.'],
    faqs: [{ question: 'How many logo concepts do I get?', answer: 'Three distinct concepts, refined with revisions until you love it.' }, { question: 'Do I own the final logo?', answer: 'Yes, you get full rights and all the source files.' }, { question: 'What files do I receive?', answer: 'Everything you need — from high-resolution formats to web and social sizes.' }, { question: 'Can I request changes?', answer: 'Yes, revisions are included until the identity feels right.' }],
  },
  'brochure-pdf': {
    description: 'A designed brochure or catalog PDF, optimized to share on WhatsApp and look great on phones.',
    details: 'A designed brochure or catalog PDF, optimized to share on WhatsApp and look great on phones.',
    benefits: ['Share a polished brochure on WhatsApp in seconds', 'Present your services professionally on any phone'],
    overview: ['A polished brochure makes your business look established and gives customers something concrete to remember you by. When it is optimized for WhatsApp, you can share it with anyone in seconds.', 'We design a clean, professional brochure or catalog PDF that reads beautifully on a phone — the way most customers will actually see it.'],
    howItWorks: ['We gather your services, story, and contact details.', 'We write and design a clean, branded layout.', 'You review and we refine the design.', 'We export a phone-friendly PDF ready to share.'],
    faqs: [{ question: 'How many pages is the brochure?', answer: 'Typically a four-page layout, with more pages available if needed.' }, { question: 'Will it look good on WhatsApp?', answer: 'Yes, it is optimized and compressed to look sharp on phones.' }, { question: 'Do I need to provide photos?', answer: 'We can use yours or source licensed images for you.' }, { question: 'Can I update it later?', answer: 'Yes, we can revise the design whenever your services change.' }],
  },
  'ordering-page': {
    description: 'An order form that drops straight into WhatsApp, so customers order without a single phone call.',
    details: 'An online order form that drops straight into WhatsApp, so customers order without a single phone call.',
    benefits: ['Let customers order without a single phone call', 'Capture orders straight into WhatsApp'],
    overview: ['Every phone call you skip is time saved and a sale made faster. An online ordering page lets customers choose what they want and send the order straight to your WhatsApp — no call required.', 'It works for restaurants, boutiques, home kitchens, and any business that takes orders. Customers fill a simple form and you receive a complete, readable order instantly.'],
    howItWorks: ['We design a simple order form for your products or menu.', 'We connect the form to your WhatsApp.', 'Customers fill in their details and order.', 'You receive the order and confirm directly.'],
    faqs: [{ question: 'Do customers need an account?', answer: 'No, they simply fill the form and send it.' }, { question: 'Can I customize the fields?', answer: 'Yes, we tailor the form to exactly what you need to know.' }, { question: 'Does it take payments?', answer: 'Orders are sent to WhatsApp, with payment links available if you want.' }, { question: 'How do I receive orders?', answer: 'They arrive in your WhatsApp, ready to confirm.' }],
  },
  'email-marketing-setup': {
    description: 'A branded newsletter template, subscriber list import, and welcome automation — ready to send.',
    details: 'Set up branded email marketing with a newsletter template, subscriber import, and welcome automation — ready to send.',
    benefits: ['Start email marketing with a professional, branded setup', 'Automate welcome emails so no subscriber goes cold'],
    overview: ['Email is one of the highest-return marketing channels, because you own the list and reach customers directly. Getting the setup right means every send looks professional and lands in the inbox.', 'We set up your platform, build a branded newsletter template, import your list, and create a welcome automation — so you are ready to send from day one.'],
    howItWorks: ['We set up your email platform and verify your sending domain.', 'We design a branded newsletter template.', 'We import and organize your subscriber list.', 'We build a welcome automation and signup form.'],
    faqs: [{ question: 'Which platform do you use?', answer: 'A popular, affordable provider like Brevo or Mailchimp.' }, { question: 'Do I need my own email list?', answer: 'We can import your existing list and help you grow it.' }, { question: 'Will my emails land in spam?', answer: 'We configure authentication and best practices to maximize delivery.' }, { question: 'Can I send campaigns myself?', answer: 'Yes, we set it up and show you how to use it.' }],
  },
  'email-marketing': {
    description: 'Monthly campaigns, A/B testing, and re-engagement that keep your list warm and buying.',
    details: 'Monthly email campaigns, A/B testing, and re-engagement that keep your list warm and buying.',
    benefits: ['Keep your list warm and buying every month', 'Reach customers directly without relying on ads'],
    overview: ['A warm email list is an asset that pays you every month. Regular, well-written campaigns keep your business top-of-mind and bring customers back without paying for ads.', 'We handle the monthly sending, testing, and optimization — so your list stays engaged and your offers keep producing sales.'],
    howItWorks: ['We plan your monthly campaign calendar.', 'We write and design each campaign.', 'We test subject lines and optimize send times.', 'We report opens, clicks, and sales monthly.'],
    faqs: [{ question: 'How many campaigns do you send?', answer: 'Two to four campaigns a month, depending on your plan.' }, { question: 'Do you write the content?', answer: 'Yes, copywriting and design are included.' }, { question: 'Can you handle seasonal offers?', answer: 'Yes, we plan campaigns around your sales calendar.' }, { question: 'How do I measure success?', answer: 'We report opens, clicks, and resulting enquiries monthly.' }],
  },
  'sms-marketing': {
    description: 'Appointment reminders, offers, and alerts delivered by SMS — with DND compliance handled.',
    details: 'Send appointment reminders, offers, and alerts by SMS — with DND and TRAI compliance handled for you.',
    benefits: ['Cut no-shows with appointment reminders', 'Reach customers instantly with offers and alerts'],
    overview: ['SMS is the fastest way to reach a customer — most messages are read within minutes. Appointment reminders cut no-shows, and offers reach customers wherever they are.', 'We handle the compliance side too, so your messages follow India’s DND and TRAI rules and reach customers without landing you in trouble.'],
    howItWorks: ['We set up your SMS platform and register your templates.', 'We ensure DND and TRAI compliance.', 'We build templates for reminders, offers, and alerts.', 'We schedule campaigns and report delivery.'],
    faqs: [{ question: 'Is SMS marketing legal in India?', answer: 'Yes, with DND and TRAI compliance, which we handle for you.' }, { question: 'What does it cost to send SMS?', answer: 'SMS credits are billed separately per message, typically a few paise each.' }, { question: 'Can I send appointment reminders?', answer: 'Yes, reminders are one of the most effective uses of SMS.' }, { question: 'Can customers opt out?', answer: 'Yes, every message includes a clear opt-out option.' }],
  },
  'blog-content': {
    description: 'Fresh, SEO-friendly blog posts that build authority and keep your site climbing.',
    details: 'Fresh, SEO-friendly blog posts that build authority and keep your website climbing.',
    benefits: ['Build authority and climb search rankings with fresh content', 'Give customers helpful answers that earn trust'],
    overview: ['Every helpful blog post is a new page that can rank on Google and earn customer trust. Consistent, SEO-friendly content builds your authority and keeps your website climbing.', 'We research topics your customers actually search for, write the articles, and publish them — so your site grows steadily without you having to write a word.'],
    howItWorks: ['We research topics and keywords worth targeting.', 'We write clear, useful articles for your audience.', 'We optimize each post for search engines.', 'We publish and report performance.'],
    faqs: [{ question: 'How many posts do I get?', answer: 'Two to four posts a month, depending on your plan.' }, { question: 'Do I need to provide topics?', answer: 'No, we research topics, but your suggestions are welcome.' }, { question: 'Will blogging help me rank?', answer: 'Yes, over time fresh, relevant content builds authority and rankings.' }, { question: 'Who writes the content?', answer: 'We write it in your brand voice, reviewed before publishing.' }],
  },
  'qr-suite': {
    description: 'A scannable QR menu plus UPI payment and WhatsApp links — print-ready for tables and counters.',
    details: 'A scannable QR menu with UPI payment and WhatsApp links — print-ready for tables and counters.',
    benefits: ['Let customers order and pay by scanning a QR code', 'Reduce wait times and manual order-taking'],
    overview: ['A single QR code can replace a printed menu, a payment terminal, and a phone call. Customers scan, browse your menu, pay via UPI, or chat on WhatsApp — all without a single step from your staff.', 'We build a mobile-friendly menu page and generate print-ready QR codes for tables, counters, and packaging.'],
    howItWorks: ['We design a mobile-friendly menu or service page.', 'We generate QR codes for menu, UPI payment, and WhatsApp.', 'We prepare print-ready posters and table stands.', 'You print and place them where customers can scan.'],
    faqs: [{ question: 'What can customers do with the QR code?', answer: 'View your menu, pay by UPI, or message you on WhatsApp.' }, { question: 'Can I update the menu later?', answer: 'Yes, digital menus can be updated anytime without reprinting.' }, { question: 'Do I get print-ready files?', answer: 'Yes, we deliver posters and table stands ready to print.' }, { question: 'Do customers need an app to scan?', answer: 'No, any phone camera can scan a QR code.' }],
  },
  'festive-campaign': {
    description: 'Ready-made festive campaigns — social posts, emails, and WhatsApp broadcasts for Diwali, Holi, and New Year.',
    details: 'Ready-made festive campaigns for Diwali, Holi, and New Year — social posts, emails, and WhatsApp broadcasts.',
    benefits: ['Capture seasonal demand when customers are ready to buy', 'Run ready-made campaigns without the busy-work'],
    overview: ['Festive seasons are when customers are most ready to spend — and when competitors fight hardest for attention. A ready-made campaign lets you capture that demand without the last-minute scramble.', 'We design a complete festive campaign for Diwali, Holi, or New Year, with social posts, emails, and WhatsApp broadcasts that feel cohesive and on-brand.'],
    howItWorks: ['We design a festive theme for your brand.', 'We create social posts, email, and WhatsApp creatives.', 'You approve the campaign and offers.', 'We schedule and launch it across channels.'],
    faqs: [{ question: 'Which festivals do you cover?', answer: 'Diwali, Holi, New Year, and other key seasons on request.' }, { question: 'How long does it take?', answer: 'We plan ahead so your campaign is ready before the season starts.' }, { question: 'Can you include a special offer?', answer: 'Yes, we design creatives around your offers and discounts.' }, { question: 'Do you run the campaigns too?', answer: 'We prepare everything and can schedule the sends for you.' }],
  },
  'appointment-booking': {
    description: 'A booking page with time slots and automatic confirmations, so customers book without phone tag.',
    details: 'A booking page with time slots and automatic confirmations, so customers book without phone tag.',
    benefits: ['End phone-tag and double bookings', 'Let customers book at any hour, automatically'],
    overview: ['Phone tag and double bookings cost you customers every week. An online booking page lets clients see your availability and book themselves — with automatic confirmations to both of you.', 'It works for salons, clinics, consultants, and any business that runs on appointments, freeing your staff to focus on serving rather than scheduling.'],
    howItWorks: ['We build a branded booking page with your services.', 'We configure your time slots and availability.', 'Customers book and receive automatic confirmations.', 'Bookings sync to your calendar instantly.'],
    faqs: [{ question: 'Can customers reschedule or cancel?', answer: 'Yes, we can enable self-service rescheduling and cancellation.' }, { question: 'Will it sync with my calendar?', answer: 'Yes, bookings sync with Google Calendar.' }, { question: 'Do I get notified of new bookings?', answer: 'Yes, via WhatsApp or email instantly.' }, { question: 'Can I set different services with different durations?', answer: 'Yes, each service can have its own duration and pricing.' }],
  },
  'ai-chatbot': {
    description: 'A 24/7 AI assistant on WhatsApp and your website that answers FAQs and hands off to a human.',
    details: 'A 24/7 AI assistant on WhatsApp and your website that answers FAQs and hands off to a human when needed.',
    benefits: ['Answer every customer instantly, 24/7', 'Free your team from repetitive FAQs'],
    overview: ['Your customers ask the same questions every day — prices, hours, directions, availability. An AI chatbot answers them instantly on WhatsApp and your website, at any hour, so no enquiry ever goes unanswered.', 'When a question is too complex, the bot hands off to a human seamlessly, so you get the speed of automation without losing the personal touch.'],
    howItWorks: ['We build a knowledge base from your FAQs and services.', 'We set up a 24/7 auto-reply flow on WhatsApp and your site.', 'We tune the bot’s tone to match your brand.', 'We review conversations monthly and refine the answers.'],
    faqs: [{ question: 'Will the bot sound human?', answer: 'Yes, we tune its tone and responses to feel natural and on-brand.' }, { question: 'Can it take bookings or orders?', answer: 'Yes, it can guide customers through simple booking or ordering flows.' }, { question: 'What happens when it cannot answer?', answer: 'It hands off to a real person so no lead is lost.' }, { question: 'Do I need to train it myself?', answer: 'No, we set it up and keep it tuned for you.' }],
  },
  'ai-content': {
    description: 'AI-assisted blogs, captions, and emails written in your brand voice — human-reviewed before publishing.',
    details: 'AI-assisted blogs, captions, and emails written in your brand voice — human-reviewed before publishing.',
    benefits: ['Publish consistent content without hiring a writer', 'Keep your brand voice human-reviewed and on-point'],
    overview: ['Consistent content grows your business, but writing it takes time you do not have. AI-assisted content produces blogs, captions, and emails quickly — then a human reviews everything before it goes live.', 'You get the speed of AI with the quality control of a real editor, all written in your brand’s voice.'],
    howItWorks: ['We set up your brand voice and style guide.', 'We generate drafts for blogs, captions, and emails.', 'A human reviews and polishes each piece.', 'We publish and track performance.'],
    faqs: [{ question: 'Is the content original?', answer: 'Yes, each piece is generated and then edited to be unique and on-brand.' }, { question: 'Does a human review everything?', answer: 'Yes, nothing is published without human review.' }, { question: 'Can it match my brand’s tone?', answer: 'Yes, we configure it to write in your voice.' }, { question: 'What formats can you produce?', answer: 'Blogs, social captions, email drafts, and meta descriptions.' }],
  },
  'ai-review-manager': {
    description: 'Auto-replies to every review with a monthly sentiment summary, so nothing goes unanswered.',
    details: 'Auto-reply to every review with a monthly sentiment summary, so no customer feedback goes unanswered.',
    benefits: ['Never leave a review unanswered', 'See how customers feel at a glance each month'],
    overview: ['Every review deserves a response, but monitoring every platform and replying promptly is hard. An AI review manager watches for new reviews and drafts appropriate replies automatically.', 'You never leave a customer unanswered, and a monthly sentiment summary shows you at a glance how customers feel about your business.'],
    howItWorks: ['We monitor Google, Facebook, and other review platforms.', 'The AI drafts a fitting reply to every review.', 'You approve replies, or let them post automatically.', 'You get a monthly summary of customer sentiment.'],
    faqs: [{ question: 'Will replies sound automatic?', answer: 'No, they are tailored to each review and tuned to your tone.' }, { question: 'Do I approve replies before they post?', answer: 'You can choose to approve first or allow automatic posting.' }, { question: 'Which platforms are covered?', answer: 'Google, Facebook, and other major review sites.' }, { question: 'What does the monthly summary show?', answer: 'Overall sentiment, common themes, and areas to improve.' }],
  },
  'ai-lead-qualifier': {
    description: 'A WhatsApp assistant that asks the right questions, scores leads, and pings you the hot ones instantly.',
    details: 'A WhatsApp assistant that asks the right questions, scores leads, and pings you the hot ones instantly.',
    benefits: ['Know which leads are hot the moment they arrive', 'Stop chasing cold leads'],
    overview: ['Not every enquiry is a customer worth chasing. An AI lead qualifier asks the right questions on WhatsApp, scores each lead, and pings you instantly when a hot one arrives.', 'You stop wasting time on tire-kickers and focus your energy on the leads most likely to buy.'],
    howItWorks: ['We build a qualification script around your sales process.', 'The assistant asks about budget, timeline, and requirements.', 'Each lead is scored hot, warm, or cold.', 'Hot leads notify you on WhatsApp immediately.'],
    faqs: [{ question: 'What questions does it ask?', answer: 'The ones that matter to your sales process — budget, timeline, and needs.' }, { question: 'How do I know which leads are hot?', answer: 'Hot leads trigger an instant WhatsApp notification to you.' }, { question: 'Can I customize the scoring?', answer: 'Yes, we tune the rules to what makes a lead valuable to you.' }, { question: 'Does it work with my existing WhatsApp?', answer: 'Yes, it runs on your business WhatsApp.' }],
  },
  'ai-product-photos': {
    description: 'Studio-quality product photos generated without a photoshoot — background, lighting, and edits done for you.',
    details: 'Studio-quality product photos generated without a photoshoot — background, lighting, and edits handled for you.',
    benefits: ['Get studio-quality product photos without a photoshoot', 'Make your catalog look premium and professional'],
    overview: ['Professional product photos used to require a studio, a photographer, and days of work. AI product photography creates studio-quality images of your products without any of that.', 'We generate clean, on-brand images with the right background and lighting, then polish them so your catalog looks premium everywhere it appears.'],
    howItWorks: ['We guide you on capturing a few simple photos of each product.', 'AI generates studio-quality backgrounds and lighting.', 'We edit, color-correct, and resize each image.', 'You receive web- and social-ready images.'],
    faqs: [{ question: 'Do I need professional equipment?', answer: 'No, a phone photo is usually enough to start.' }, { question: 'How many photos can I get?', answer: 'We work in batches, typically around ten per run.' }, { question: 'Can you match my brand style?', answer: 'Yes, we tailor backgrounds and tone to your brand.' }, { question: 'Are the images high resolution?', answer: 'Yes, they are suitable for web and social media.' }],
  },
  'custom-software': {
    description: 'Dashboards, CRMs, and internal tools built to your exact workflow.',
    details: 'Dashboards, CRMs, and internal tools built to your exact workflow — from discovery to deployment and support.',
    benefits: ['Get software built around your exact workflow', 'Automate the busy-work eating your team\'s time'],
    overview: ['Off-the-shelf software forces your business to work the tool’s way. Custom software does the opposite — it is built around your exact workflow, from the screens your team uses to the reports you need.', 'Whether it is a dashboard, CRM, or internal tool, we take it from discovery to launch, then train your team and support you after go-live.'],
    howItWorks: ['We run a discovery session to map your workflow and goals.', 'We design screens and get your feedback before building.', 'We build, test, and refine the software iteratively.', 'We launch, train your team, and support you afterwards.'],
    faqs: [{ question: 'How long does custom software take?', answer: 'It depends on scope, but we agree a timeline during discovery.' }, { question: 'How is the price determined?', answer: 'Pricing is quote-based, estimated from your requirements.' }, { question: 'Do I own the software?', answer: 'Yes, the software is built for your business.' }, { question: 'What happens after launch?', answer: 'We provide training and support to keep things running smoothly.' }],
  },
  'billing-invoicing': {
    description: 'GST invoices, payment tracking, and recurring billing — with UPI links on every invoice.',
    details: 'GST invoices, payment tracking, and recurring billing with UPI links on every invoice.',
    benefits: ['Send GST-compliant invoices and get paid faster', 'See who owes what at a glance'],
    overview: ['Getting paid on time starts with clear, professional invoices. A billing system generates GST-compliant invoices, tracks payments, and sends reminders automatically.', 'You always know who owes what, and customers can pay instantly with a UPI link on every invoice.'],
    howItWorks: ['We build your invoice templates with GST details.', 'You create customers and items once.', 'Invoices go out with UPI payment links.', 'Payments are tracked and reported automatically.'],
    faqs: [{ question: 'Are the invoices GST-compliant?', answer: 'Yes, with CGST, SGST, and IGST breakdowns.' }, { question: 'Can customers pay online?', answer: 'Yes, every invoice includes a UPI payment link.' }, { question: 'Can I handle recurring billing?', answer: 'Yes, for subscriptions and retainers.' }, { question: 'What reports do I get?', answer: 'Revenue, outstanding amounts, and GST summaries.' }],
  },
}
